version: '3.7'
services:
  postgres:
    image: debezium/postgres:13
    ports:
      - 5432:5432
    volumes:
      - ./app:/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=borzoi
      - POSTGRES_DB=db_user_account
    
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5051:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=kurialancelot@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=borzoi
    depends_on:
      - postgres
    restart: always
  
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.1
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always
  
  kafka:
    image: confluentinc/cp-enterprise-kafka:6.2.1
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9991
    depends_on: [zookeeper]
    restart: always
  
  debezium:
    image: debezium/connect:1.6
    ports:
      - 8083:8083
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      # CONFIG_STORAGE_TOPIC: debezium_connect_config
      CONFIG_STORAGE_TOPIC: connect_configs
      # OFFSET_STORAGE_TOPIC: debezium_connect_offsets
      OFFSET_STORAGE_TOPIC: connect_offsets
      # KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      KEY_CONVERTER: io.confluent.connect.avro.AvroConverter

      # VALUE_CONVERTER: io.debezium.connector.postgresql.converters.JsonConverter
      VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      STATUS_STORAGE_TOPIC: debezium_connect_status
      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_FLUSH_INTERVAL_MS: 60000
    depends_on: [kafka]
    restart: always
  
  schema-registry:
    image: confluentinc/cp-schema-registry:6.2.1
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://localhost:8081, http://schema-registry:8081
    depends_on: [zookeeper,kafka]
    restart: always

# kafka_manager:
#   image: hlebalbau/kafka-manager:stable
#   restart: always
#   ports:
#     "9000:9000" 
#   depends_on: [zookeeper, kafka]

#   environment:
#     ZK_HOSTS: "Zookeeper: 2181"
#     APPLICATION_SECRET: "random-secret"
#   command: -Dpidfile.path=/dev/null




  # docker-compose up -d
  # curl -i -X POST -H "Accept:application/json" -H "Content-Type:application/json" 127.0.0.1:8083/connectors --data "@debezium.json" 




# docker run --tty --network ms-spring-boot-debezium-master-slave_default confluentinc/cp-enterprise-kafka:6.2.1 kafka-console-consumer --bootstrap-serverkafka:9092 --topic postgres.public.employee --from-beginning


# https://chatgpt.com/share/7f1a060e-37de-4a8a-98c9-2cbcafb2ebe8
# personal access token: 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
git remote set-url origin https://kuriofoolio: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
@github.com/kuriofoolio/ms-user-account-service.git